name: goreleaser

on:
  push:
    tags:
      - "v[0-9].[0-9].[0-9]"
      - "v[0-9].[0-9].[0-9]-rc.[0-9]"
      - "v[0-9].[0-9].[0-9]-alpha.[0-9]"

permissions:
  contents: write
  packages: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.0'
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6.3.0
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean
          workdir: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}